spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        bootstrap: true
        git:
          clone-on-start: true
          default-label: master
          uri: https://github.com/ashish-tiwari-11/banking-microservice-configuration.git