spring:
  config:
    import: 'optional:configserver:http://localhost:8080'
  application:
    name: accountservice
  datasource:
    url: 'jdbc:oracle:thin:@localhost:1521/myOracleDB'
    username: SYSTEM
    password: aceEM@11
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  file:
    name: 'D:/intelliJ-workspace/logs/application.log'

management:
  health:
    circuitbreakers:
      enable: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      accountCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
#  retry:
#    instances:
#      customerCB:
#        registerHealthIndicator: true
#        maxRetryAttempts: 5
#        waitDuration: 10s
#  ratelimiter:
#    instances:
#      customerCB:
#        registerHealthIndicator: false
#        limitForPeriod: 10
#        limitRefreshPeriod: 10s
#        timeoutDuration: 3s