spring:
  config:
    import: "optional:configserver:http://localhost:8080"
  application:
    name: customerservice
  datasource:
    url: jdbc:mysql://localhost:3306/bankingms
    username: root
    password: aceEM@11
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8081

info:
  app:
    name: Customer Service App
    description: A domain based microservice
    version: 1.0.0
