spring:
  config:
    import: "optional:configserver:http://localhost:8080"
  application:
    name: customerservice
info:
  app:
    name: Customer Service App
    description: A domain based microservice
    version: 1.0.0
