spring:
  application:
    name: BankingGateway
  config:
    import: "optional:configserver:http://localhost:8080"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ACCOUNTSERVICE
          uri: lb://ACCOUNTSERVICE
          predicates:
            - Path=/api/v1/account/**
#            - Path=/api/v1/account/**/**
        - id: CUSTOMERSERVICE
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/api/v1/customer/**
#            - Path=/api/v1/customer/**/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Gateway Server Microservice
    description: Microservice example for Bootcamp
    version: 1.0.0

logging:
  level:
    com:
      jpmchase:
        cib:
          bankinggateway: debug