version: "3.8"
services:
  server:
    build: .
    image: customerservicejar
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0-debian
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: bankingms
      MYSQL_ROOT_PASSWORD: aceEM@11