spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8080"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false